### ISSUE TITLE
Dependency details in Readme file

### ISSUE THREAD

**Issue by JoyceBabu** [gporais/gXipmsg#1]
It would be helpful if you could specify that openmotif development files are required for compiling gXipmsg. On ubuntu I was able to install it with

```
sudo aptitude install libmotif-dev
```

On Redhat based systems I think think the command is 

```
sudo yum install openmotif-devel
```

**Comment by gporais** [comment]
Hi Joyce! Thanks for the feedback :) I didn't expect this so please excuse me if my way of answering is a bit non professional. Anyway, about your feedback, that's indeed a good idea! I will update the Readme file soon, thanks ;)
Also the reason is only got Ubuntu on my VMware and i thought all Linux distro are the same. So i guess for the mean time ill take this two lines from you (ubuntu and redhat). I should have done this for the BSD's hmm

**Comment by JoyceBabu** [comment]
Apologies for the late reply, I thought I had already replied.

Don't worry, I am also new to all these and don't know which is professional and which is not :) .

I haven't tested it on RedHat, but a quick Google search returned that the package name is openmotif-devel on RedHat/CentOS.
